INTEREST_OPTIONS = [
    "Mathematics",
    "Creative Writing",
    "Biology",
    "Robotics",
    "Music Theory",
    "World History",
    "Computer Programming",
    "Environmental Science",
    "Public Speaking",
    "Theater Arts",
    "Astronomy",
    "Psychology",
    "Film Studies",
    "Chemistry",
    "Political Science",
    "Entrepreneurship",
    "Photography",
    "Philosophy",
    "Statistics",
    "Debate",
    "Forensic Science",
    "Sociology",
    "Graphic Design",
    "Economics",
    "Physics",
    "Marine Biology",
    "UX Design",
    "Digital Media",
    "Artificial Intelligence",
    "Game Development",
    "Ethics",
    "Anthropology",
    "Web Development",
    "Linguistics",
    "Cognitive Science",
    "Marketing",
    "Botany",
    "Data Science",
    "Education Policy",
    "Foreign Languages",
    "Geology",
    "Journalism",
    "Music Performance",
    "Gender Studies",
    "Classical Studies",
    "Animation",
    "Social Work",
    "Nanotechnology",
    "Criminal Justice",
    "Zoology"
]
